"use client";

import { useState } from "react";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { 
  Bot, 
  Sparkles, 
  RotateCcw, 
  FileText, 
  TrendingUp,
  Home,
  ArrowLeft
} from "lucide-react";
import Link from "next/link";
import { ChatWidget } from "@/components/ai/chat-widget";
import { MemoryRibbon } from "@/components/ai/memory-ribbon";
import { KpiCard, sampleKpiData } from "@/components/charts/kpi-card";
import { useDemoStore } from "@/lib/demo-store";

export default function DemoPage() {
  const [showBriefing, setShowBriefing] = useState(false);
  const { preferences, satisfactionScore, reworkRate, preferencesLearned } = useDemoStore();

  const generateBriefing = () => {
    setShowBriefing(true);
  };

  const briefingContent = `
**Pre-Visit Briefing - Customer #12847**
*Generated by AI Maid Assistant*

**Customer Preferences:**
${preferences.filter(p => p.active).map(p => `• ${p.label} (${p.category})`).join('\n')}

**Special Instructions:**
- Use only unscented, bleach-free products due to allergies
- Cat (Whiskers) is friendly and does not need to be contained
- Exercise extra care around antique furniture in living room
- Ensure side gate is locked upon departure for security

**Crew Notes:**
- Customer has been very satisfied with recent visits
- Pay attention to detail on antique pieces
- Previous crew noted customer appreciates thorough bathroom cleaning

**Emergency Contact:** Available via app
**Estimated Duration:** 2.5 hours
**Special Equipment:** Bring hypoallergenic cleaning supplies
  `;

  return (
    <div className="min-h-screen bg-background">
      {/* Header */}
      <header className="border-b bg-background/80 backdrop-blur-md sticky top-0 z-50">
        <div className="container mx-auto px-4 sm:px-6 lg:px-8">
          <div className="flex h-16 items-center justify-between">
            <div className="flex items-center gap-4">
              <Button variant="ghost" size="sm" asChild>
                <Link href="/">
                  <ArrowLeft className="w-4 h-4 mr-2" />
                  Back to Site
                </Link>
              </Button>
              <div className="flex items-center gap-2">
                <Bot className="w-6 h-6 text-primary" />
                <span className="font-display font-bold text-lg">AI Maid Demo</span>
                <Badge variant="secondary">Interactive Preview</Badge>
              </div>
            </div>
            <Button
              variant="outline"
              size="sm"
              onClick={() => useDemoStore.getState().resetDemo()}
            >
              <RotateCcw className="w-4 h-4 mr-2" />
              Reset Demo
            </Button>
          </div>
        </div>
      </header>

      <div className="container mx-auto px-4 sm:px-6 lg:px-8 py-8">
        {/* Hero */}
        <div className="text-center mb-8">
          <h1 className="text-display-lg font-bold text-foreground mb-4 font-display">
            AI Maid Assistant Demo
          </h1>
          <p className="text-lg text-muted-foreground max-w-2xl mx-auto">
            Experience how our AI learns your preferences and creates personalized cleaning briefs. 
            This is a safe, client-side demo with no real data collection.
          </p>
        </div>

        {/* Main Demo Interface */}
        <div className="grid grid-cols-1 lg:grid-cols-2 gap-8 mb-8">
          {/* Left Column - Chat */}
          <div>
            <ChatWidget />
          </div>

          {/* Right Column - Preferences & Insights */}
          <div className="space-y-6">
            {/* Memory Ribbon */}
            <Card>
              <CardHeader>
                <CardTitle className="flex items-center gap-2">
                  <Sparkles className="w-5 h-5 text-primary" />
                  Learned Preferences
                </CardTitle>
              </CardHeader>
              <CardContent>
                <MemoryRibbon interactive />
              </CardContent>
            </Card>

            {/* KPI Cards */}
            <div className="grid grid-cols-1 sm:grid-cols-3 gap-4">
              <KpiCard
                title="Satisfaction"
                value={satisfactionScore.toFixed(1)}
                delta={{
                  value: 12,
                  label: "vs baseline",
                  trend: "up",
                }}
                chart={{
                  type: "area",
                  data: [
                    { value: 4.2 },
                    { value: 4.3 },
                    { value: 4.5 },
                    { value: 4.6 },
                    { value: 4.7 },
                    { value: satisfactionScore },
                  ],
                }}
              />
              <KpiCard
                title="Rework Rate"
                value={`${reworkRate.toFixed(1)}%`}
                delta={{
                  value: -35,
                  label: "improvement",
                  trend: "down",
                }}
                chart={{
                  type: "line",
                  data: [
                    { value: 5.2 },
                    { value: 4.1 },
                    { value: 3.5 },
                    { value: 2.8 },
                    { value: 2.3 },
                    { value: reworkRate },
                  ],
                }}
              />
              <KpiCard
                title="Preferences"
                value={preferencesLearned.toString()}
                delta={{
                  value: 23,
                  label: "this month",
                  trend: "up",
                }}
                chart={{
                  type: "area",
                  data: [
                    { value: 12 },
                    { value: 19 },
                    { value: 25 },
                    { value: 31 },
                    { value: 38 },
                    { value: preferencesLearned },
                  ],
                }}
              />
            </div>
          </div>
        </div>

        {/* Crew Briefing Demo */}
        <Card>
          <CardHeader>
            <CardTitle className="flex items-center gap-2">
              <FileText className="w-5 h-5 text-primary" />
              Generated Crew Briefing
            </CardTitle>
            <p className="text-sm text-muted-foreground">
              See how your preferences become actionable instructions for cleaning crews
            </p>
          </CardHeader>
          <CardContent>
            {!showBriefing ? (
              <div className="text-center py-8">
                <div className="bg-muted/50 rounded-lg p-8 mb-4">
                  <FileText className="w-12 h-12 text-muted-foreground mx-auto mb-4" />
                  <p className="text-muted-foreground mb-4">
                    Generate a personalized crew briefing based on your current preferences
                  </p>
                  <Button onClick={generateBriefing} className="group">
                    Generate Briefing
                    <Sparkles className="w-4 h-4 ml-2 group-hover:animate-pulse" />
                  </Button>
                </div>
              </div>
            ) : (
              <div className="space-y-4">
                <div className="flex items-center justify-between">
                  <Badge variant="secondary" className="flex items-center gap-1">
                    <Bot className="w-3 h-3" />
                    AI Generated
                  </Badge>
                  <Button
                    variant="outline"
                    size="sm"
                    onClick={() => setShowBriefing(false)}
                  >
                    <RotateCcw className="w-3 h-3 mr-1" />
                    Regenerate
                  </Button>
                </div>
                
                <div className="bg-muted/30 rounded-lg p-4 font-mono text-sm whitespace-pre-line">
                  {briefingContent}
                </div>
                
                <div className="bg-green-50 dark:bg-green-900/20 border border-green-200 dark:border-green-800 rounded-lg p-4">
                  <div className="flex items-center gap-2 mb-2">
                    <TrendingUp className="w-4 h-4 text-green-600" />
                    <span className="font-semibold text-green-800 dark:text-green-200">
                      Impact Prediction
                    </span>
                  </div>
                  <p className="text-sm text-green-700 dark:text-green-300">
                    This briefing is predicted to improve satisfaction by 15% and reduce rework probability by 40% based on similar preference profiles.
                  </p>
                </div>
              </div>
            )}
          </CardContent>
        </Card>

        {/* Demo Features */}
        <div className="mt-12">
          <h2 className="text-2xl font-bold text-center mb-8 font-display">
            Demo Features
          </h2>
          
          <Tabs defaultValue="chat" className="max-w-4xl mx-auto">
            <TabsList className="grid w-full grid-cols-3">
              <TabsTrigger value="chat">AI Chat</TabsTrigger>
              <TabsTrigger value="memory">Memory System</TabsTrigger>
              <TabsTrigger value="briefing">Crew Briefing</TabsTrigger>
            </TabsList>
            
            <TabsContent value="chat" className="space-y-4">
              <Card>
                <CardContent className="pt-6">
                  <h3 className="font-semibold mb-2">Interactive AI Assistant</h3>
                  <p className="text-sm text-muted-foreground mb-4">
                    Try different types of feedback and see how the AI extracts structured preferences:
                  </p>
                  <ul className="text-sm space-y-1 text-muted-foreground">
                    <li>• Mention allergies or sensitivities</li>
                    <li>• Describe your pets and their behavior</li>
                    <li>• Share access instructions or security preferences</li>
                    <li>• Note special care items or areas of focus</li>
                  </ul>
                </CardContent>
              </Card>
            </TabsContent>
            
            <TabsContent value="memory" className="space-y-4">
              <Card>
                <CardContent className="pt-6">
                  <h3 className="font-semibold mb-2">Preference Learning</h3>
                  <p className="text-sm text-muted-foreground mb-4">
                    Watch how your preferences are categorized and stored:
                  </p>
                  <ul className="text-sm space-y-1 text-muted-foreground">
                    <li>• <strong>Products:</strong> Cleaning supplies, scents, allergies</li>
                    <li>• <strong>Access:</strong> Keys, gates, security systems</li>
                    <li>• <strong>Pets:</strong> Behavior, containment, special needs</li>
                    <li>• <strong>Special:</strong> Delicate items, focus areas</li>
                  </ul>
                </CardContent>
              </Card>
            </TabsContent>
            
            <TabsContent value="briefing" className="space-y-4">
              <Card>
                <CardContent className="pt-6">
                  <h3 className="font-semibold mb-2">Crew Communication</h3>
                  <p className="text-sm text-muted-foreground mb-4">
                    See how preferences become actionable crew instructions:
                  </p>
                  <ul className="text-sm space-y-1 text-muted-foreground">
                    <li>• Personalized cleaning protocols</li>
                    <li>• Product and equipment recommendations</li>
                    <li>• Safety and access instructions</li>
                    <li>• Quality checkpoints and focus areas</li>
                  </ul>
                </CardContent>
              </Card>
            </TabsContent>
          </Tabs>
        </div>

        {/* CTA */}
        <div className="text-center mt-12 p-8 bg-gradient-to-r from-primary/5 via-primary/10 to-primary/5 rounded-2xl">
          <h3 className="text-xl font-bold mb-4 font-display">
            Ready for the real thing?
          </h3>
          <p className="text-muted-foreground mb-6">
            Experience AI-powered cleaning with real crews in the Dallas area.
          </p>
          <div className="flex flex-col sm:flex-row gap-4 justify-center">
            <Button size="lg" asChild>
              <Link href="/book-beta">
                <Home className="w-4 h-4 mr-2" />
                Book Beta Service
              </Link>
            </Button>
            <Button size="lg" variant="outline" asChild>
              <Link href="/careers">
                Join Our Team
              </Link>
            </Button>
          </div>
        </div>
      </div>
    </div>
  );
}
